_name_or_path:
    value: /home/yerong2/.cache/modelscope/hub/qwen/Qwen2___5-7B
_wandb:
    value:
        cli_version: 0.18.1
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
                - 105
            "3":
                - 7
                - 13
                - 19
                - 23
                - 55
                - 66
            "4": 3.11.9
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.18.1
            "13": linux-x86_64
acc_strategy:
    value: token
accelerator_config:
    value:
        dispatch_batches: false
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.95
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
additional_saved_files:
    value: []
architectures:
    value:
        - Qwen2ForCausalLM
attention_dropout:
    value: 0
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: true
bf16_full_eval:
    value: false
bos_token_id:
    value: 151643
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: 42
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 1
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: nccl
ddp_broadcast_buffers:
    value: false
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: false
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value:
        bf16:
            enabled: auto
        fp16:
            enabled: auto
            hysteresis: 2
            initial_scale_power: 16
            loss_scale: 0
            loss_scale_window: 1000
            min_loss_scale: 1
        gradient_accumulation_steps: auto
        gradient_clipping: auto
        optimizer:
            params:
                betas: auto
                eps: auto
                lr: auto
                weight_decay: auto
            type: AdamW
        scheduler:
            params:
                total_num_steps: auto
                warmup_num_steps: auto
            type: WarmupCosineLR
        steps_per_print: 2000
        train_batch_size: auto
        train_micro_batch_size_per_gpu: auto
        wall_clock_breakdown: false
        zero_optimization:
            allgather_bucket_size: 2e+08
            allgather_partitions: true
            contiguous_gradients: true
            offload_optimizer:
                device: none
                pin_memory: true
            overlap_comm: true
            reduce_bucket_size: 2e+08
            reduce_scatter: true
            stage: 2
disable_tqdm:
    value: false
dispatch_batches:
    value: null
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 151643
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 100
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
evaluation_strategy:
    value: null
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
generation_config:
    value:
        _from_model_config: false
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: 151643
        cache_config: null
        cache_implementation: null
        constraints: null
        decoder_start_token_id: null
        diversity_penalty: 0
        do_sample: false
        dola_layers: null
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        encoder_repetition_penalty: 1
        eos_token_id: 151643
        epsilon_cutoff: 0
        eta_cutoff: 0
        exponential_decay_length_penalty: null
        force_words_ids: null
        forced_bos_token_id: null
        forced_decoder_ids: null
        forced_eos_token_id: null
        guidance_scale: null
        length_penalty: 1
        low_memory: null
        max_length: 20
        max_matching_ngram_size: null
        max_new_tokens: 2048
        max_time: null
        min_length: 0
        min_new_tokens: null
        min_p: null
        no_repeat_ngram_size: 0
        num_assistant_tokens: 5
        num_assistant_tokens_schedule: heuristic
        num_beam_groups: 1
        num_beams: 1
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_logits: null
        output_scores: false
        pad_token_id: 151643
        penalty_alpha: null
        prompt_lookup_num_tokens: null
        remove_invalid_values: false
        renormalize_logits: false
        repetition_penalty: 1
        return_dict_in_generate: false
        return_legacy_cache: true
        sequence_bias: null
        stop_strings: null
        suppress_tokens: null
        temperature: 1
        token_healing: false
        top_k: 50
        top_p: 1
        transformers_version: 4.44.2
        typical_p: 1
        use_cache: true
        watermarking_config: null
generation_max_length:
    value: null
generation_num_beams:
    value: null
gradient_accumulation_steps:
    value: 16
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hidden_act:
    value: silu
hidden_size:
    value: 3584
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
intermediate_size:
    value: 18944
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.0001
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /home/yerong2/representation-engineering/lorra_finetune/qwfine/output/qwen2_5-7b/v21-20240927-205116/runs
logging_first_step:
    value: true
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
loss_name:
    value: null
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 0.5
max_length:
    value: 20
max_position_embeddings:
    value: 131072
max_steps:
    value: 200
max_window_layers:
    value: 28
metric_for_best_model:
    value: loss
metric_warmup_step:
    value: 0
min_length:
    value: 0
model/num_parameters:
    value: 7619057152
model_type:
    value: qwen2
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_attention_heads:
    value: 28
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 28
num_key_value_heads:
    value: 4
num_return_sequences:
    value: 1
num_train_epochs:
    value: 1
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /home/yerong2/representation-engineering/lorra_finetune/qwfine/output/qwen2_5-7b/v21-20240927-205116
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: /home/yerong2/.cache/modelscope/hub/qwen/Qwen2___5-7B
            bias: none
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_dropout: 0.05
            lora_dtype: null
            lorap_emb_lr: 1e-06
            lorap_lr_ratio: null
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: []
            peft_type: LORA
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - k_proj
                - v_proj
                - q_proj
            task_type: CAUSAL_LM
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 1
per_device_train_batch_size:
    value: 1
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
predict_with_generate:
    value: false
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-06
rope_theta:
    value: 1e+06
run_name:
    value: /home/yerong2/representation-engineering/lorra_finetune/qwfine/output/qwen2_5-7b/v21-20240927-205116
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 100
save_strategy:
    value: steps
save_total_limit:
    value: 2
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sliding_window:
    value: null
sortish_sampler:
    value: false
split_batches:
    value: null
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: bfloat16
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
train_dataset_sample:
    value: -1
train_sampler_random:
    value: true
transformers_version:
    value: 4.44.2
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
use_mrope:
    value: false
use_sliding_window:
    value: false
vocab_size:
    value: 152064
warmup_ratio:
    value: 0.03
warmup_steps:
    value: 0
weight_decay:
    value: 0.1
